theme = "blowfish"
baseURL = "https://eddywiyatno.my.id/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true

ignoreFiles = ["content/projects/.*", "content/journals/.*", "content/how-to/.*", "content/packages/.*"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
