theme = "blowfish"
baseURL = "https://eddywiyatno.my.id/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
