[[main]]
  name = "Products"
  pageRef = "projects"
  weight = 5

[[main]]
  name = "Journals"
  pageRef = "journals"
  weight = 10

[[main]]
  name = "How-To"
  pageRef = "how-to"
  weight = 15

[[main]]
  name = "Download"
  pageRef = "packages"
  weight = 18

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 25

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/edkas07-oss"
  weight = 100

[[footer]]
  name = "Products"
  pageRef = "projects"
  weight = 5

[[footer]]
  name = "Journals"
  pageRef = "journals"
  weight = 10

[[footer]]
  name = "How-To"
  pageRef = "how-to"
  weight = 15

[[footer]]
  name = "Download"
  pageRef = "packages"
  weight = 18

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 25


