[[main]]
  name = "Articles"
  pageRef = "articles"
  url = "/articles/"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  url = "/projects/"
  weight = 15

[[main]]
  name = "How-To"
  pageRef = "how-to"
  url = "/how-to/"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  url = "/contact/"
  weight = 25

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/edkas07-oss"
  weight = 100

[[footer]]
  name = "Articles"
  pageRef = "articles"
  url = "/articles/"
  weight = 10

[[footer]]
  name = "Projects"
  pageRef = "projects"
  url = "/projects/"
  weight = 15

[[footer]]
  name = "How-To"
  pageRef = "how-to"
  url = "/how-to/"
  weight = 20

[[footer]]
  name = "Contact"
  pageRef = "contact"
  url = "/contact/"
  weight = 25
